Update gradle.yml

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -12,8 +12,24 @@ jobs:
     steps:
       - name: Check Path
         run: |
-          pwd
-          ls -a
+          project_dir=$(find / -type d -name "yorokorom" 2>/dev/null | head -n 1)
+      
+          if [ -n "$project_dir" ]; then
+            cd "$project_dir"
+            if [ -f "docker-compose.yml" ]; then
+              pwd
+               echo "yorokorom list is.............."
+              ls -a ./yorokorom
+              docker-compose up -d
+            else
+              echo "Couldn't find 'docker-compose.yml' in the 'yorokorom' directory."
+              exit 1
+            fi
+          else
+            echo "Couldn't find the 'yorokorom' directory."
+            exit 1
+          fi
+          
 
 
   build-frontend:
