Update gradle.yml

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -44,5 +44,15 @@ jobs:
     steps:
       - name: Deploy
         run: |
-           cd /home/runner/work/yorokorom/yorokorom && docker-compose up -d
+           # 현재 위치에서부터 상위 디렉토리에서부터 찾기 시작
+           project_dir=$(find . -type d -name "yorokorom" | head -n 1)
+            if [ -n "$project_dir" ]; then
+              cd "$project_dir"
+              pwd
+              ls -a
+              docker-compose up -d
+            else
+              echo "Couldn't find the 'yorokorom' directory."
+              exit 1
+            fi
           
